Command `build -v --arch solana`:
COMPILING build_include_exclude_stdlib to SOLANA
Move source code errors Failed to compile Move into SOLANA ERROR
[0m[1m[38;5;9merror[0m[1m: unbound module[0m
  [0m[34m┌─[0m ./sources/UseSigner.move:3:7
  [0m[34m│[0m
[0m[34m3[0m [0m[34m│[0m   use [0m[31mstd::signer[0m;
  [0m[34m│[0m       [0m[31m^^^^^^^^^^^[0m [0m[31mInvalid 'use'. Unbound module: '(std=0x1)::signer'[0m

[0m[1m[38;5;9merror[0m[1m: unbound module[0m
  [0m[34m┌─[0m ./sources/UseSigner.move:6:5
  [0m[34m│[0m
[0m[34m6[0m [0m[34m│[0m     [0m[31msigner[0m::address_of(account)
  [0m[34m│[0m     [0m[31m^^^^^^[0m [0m[31mUnbound module alias 'signer'[0m


Error: Move source code errors
Command `-d -v build --arch solana`:
COMPILING MoveStdlib, build_include_exclude_stdlib to SOLANA
