processed 4 tasks

task 1 'run'. lines 25-32:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: New([0])} }} }


task 2 'run'. lines 34-42:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: Delete} }} }


task 3 'run'. lines 44-52:
ChangeSet: ChangeSet { accounts: {} }

