processed 4 tasks

task 1 'run'. lines 31-45:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000042: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R1"), type_params: [] }: New([0]), StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R2"), type_params: [Bool] }: New([1]), StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R2"), type_params: [U64] }: New([112, 0, 0, 0, 0, 0, 0, 0])} }} }


task 2 'run'. lines 47-55:
ChangeSet: ChangeSet { accounts: {0000000000000000000000000000000a: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R1"), type_params: [] }: New([0]), StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R2"), type_params: [Bool] }: New([1]), StructTag { address: 00000000000000000000000000000042, module: Identifier("M"), name: Identifier("R2"), type_params: [U64] }: New([112, 0, 0, 0, 0, 0, 0, 0])} }} }


task 3 'run'. lines 57-65:
ChangeSet: ChangeSet { accounts: {} }

