processed 4 tasks

task 1 'run'. lines 30-37:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: New([0])} }} }


task 2 'run'. lines 39-47:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: Modify([1, 42, 0, 0, 0, 0, 0, 0, 0])} }} }


task 3 'run'. lines 49-57:
ChangeSet: ChangeSet { accounts: {} }

