processed 4 tasks

task 1 'run'. lines 35-42:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: New([2, 100, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0])} }} }


task 2 'run'. lines 44-52:
ChangeSet: ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("M"), name: Identifier("R"), type_params: [] }: Modify([2, 44, 1, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0])} }} }


task 3 'run'. lines 54-62:
ChangeSet: ChangeSet { accounts: {} }

