[package]
name = "language-benchmarks"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move language benchmarks"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
criterion = "0.3.4"
criterion-cpu-time = "0.1.0"
move-binary-format = { path = "../move-binary-format" }
once_cell = "1.7.2"
proptest = "1.0.0"

move-bytecode-verifier = { path = "../move-bytecode-verifier" }
move-compiler = { path = "../move-compiler" }
move-core-types = { path = "../move-core/types" }
move-stdlib = { path = "../move-stdlib" }
move-vm-runtime = { path = "../move-vm/runtime" }
move-vm-test-utils = { path = "../move-vm/test-utils" }
move-vm-types = { path = "../move-vm/types" }

[[bench]]
name = "vm_benches"
harness = false
