[package]
name = "move-disassembler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Print a human-readable version of Move bytecode (.mv files)"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
colored = "2.0.0"
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-source-map = { path = "../../move-ir-compiler/move-bytecode-source-map" }

move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-command-line-common = { path = "../../move-command-line-common" }
move-compiler = { path = "../../move-compiler" }
move-core-types = { path = "../../move-core/types" }
move-coverage = { path = "../move-coverage" }
move-ir-types = { path = "../../move-ir/types" }

clap = { version = "3.1.8", features = ["derive"] }

[features]
default = []
