[package]
name = "move-coverage"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem Move VM code coverage"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.1.8", features = ["derive"] }
codespan = { version = "0.11.1", features = ["serialization"] }
colored = "2.0.0"
once_cell = "1.7.2"
petgraph = "0.5.1"
serde = { version = "1.0.124", default-features = false }

bcs = { workspace = true }
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-source-map = { path = "../../move-ir-compiler/move-bytecode-source-map" }

move-command-line-common = { path = "../../move-command-line-common" }
move-core-types = { path = "../../move-core/types" }
move-ir-types = { path = "../../move-ir/types" }

[features]
default = []
