[package]
name = "serializer-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem serializer tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
move-binary-format = { path = "../", features = ["fuzzing"] }

[features]
fuzzing = ["move-binary-format/fuzzing"]
