publishing Actor
publishing Runtime
publishing bcs
publishing vector
publishing AccountStateMachine
actor 0x4 created from 0x3::AccountStateMachine
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x4] := New("[00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x5 created from 0x3::AccountStateMachine
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x5] := New("[00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x4 handling 0x3::AccountStateMachine::start (hash=0x92F2AC538694747C)
  SUCCESS
  sent 0x4 <- 0xC77C4D9790CFB31 argc=1
  sent 0x5 <- 0xC77C4D9790CFB31 argc=1
  sent 0x4 <- 0x7610736AAA3EF2B1 argc=2
  sent 0x4 <- 0xC54E709381B8D1B7 argc=0
  sent 0x5 <- 0xC54E709381B8D1B7 argc=0
actor 0x5 handling 0x3::AccountStateMachine::start (hash=0x92F2AC538694747C)
  SUCCESS
actor 0x4 handling 0x3::AccountStateMachine::deposit (hash=0xC77C4D9790CFB31)
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x4] := Modify("[64, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x5 handling 0x3::AccountStateMachine::deposit (hash=0xC77C4D9790CFB31)
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x5] := Modify("[64, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x4 handling 0x3::AccountStateMachine::xfer (hash=0x7610736AAA3EF2B1)
  SUCCESS
  sent 0x5 <- 0xCF8B6BB2C0E4D96B argc=3
  commit 0x3::AccountStateMachine::AccountStateMachine[0x4] := Modify("[64, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 14, 00, 00, 00, 00, 00, 00, 00, A0, 69, 62, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x4 handling 0x3::AccountStateMachine::cleanup (hash=0xC54E709381B8D1B7)
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x4] := Modify("[64, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 14, 00, 00, 00, 00, 00, 00, 00, A0, 69, 62, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x5 handling 0x3::AccountStateMachine::cleanup (hash=0xC54E709381B8D1B7)
  SUCCESS
  commit 0x3::AccountStateMachine::AccountStateMachine[0x5] := Modify("[64, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x5 handling 0x3::AccountStateMachine::xfer_deposit (hash=0xCF8B6BB2C0E4D96B)
  SUCCESS
  sent 0x4 <- 0xA2A5E15322031DAA argc=1
  commit 0x3::AccountStateMachine::AccountStateMachine[0x5] := Modify("[78, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x4 handling 0x3::AccountStateMachine::xfer_finish (hash=0xA2A5E15322031DAA)
  SUCCESS
  sent 0x4 <- 0xED086F5DD31AF3B3 argc=0
  commit 0x3::AccountStateMachine::AccountStateMachine[0x4] := Modify("[50, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00]")
actor 0x4 handling 0x3::AccountStateMachine::end (hash=0xED086F5DD31AF3B3)
  SUCCESS
  sent 0x4 <- 0x54B7C3C53C16727A argc=1
  sent 0x5 <- 0x54B7C3C53C16727A argc=1
  sent 0x5 <- 0x54B7C3C53C16727A argc=1
actor 0x4 handling 0x3::AccountStateMachine::verify (hash=0x54B7C3C53C16727A)
  SUCCESS
actor 0x5 handling 0x3::AccountStateMachine::verify (hash=0x54B7C3C53C16727A)
  SUCCESS
actor 0x5 handling 0x3::AccountStateMachine::verify (hash=0x54B7C3C53C16727A)
  FAIL  VMError with status ABORTED with sub status 2 at location Module ModuleId { address: 0x3, name: Identifier("AccountStateMachine") } and message 0x3::AccountStateMachine::verify at offset 7 at code offset 7 in function definition 16
