Running Move unit tests
[ FAIL    ] 0x1::MissingData::missing_data
[ FAIL    ] 0x1::MissingData::missing_data_from_other_function

Test failures:

Failures in 0x1::MissingData:

┌── missing_data ──────
│ ITE: An unknown error was reported. Location: 
│ VMError (if there is one): 
└──────────────────


┌── missing_data_from_other_function ──────
│ ITE: An unknown error was reported. Location: 
│ VMError (if there is one): 
└──────────────────

Test result: FAILED. Total tests: 2; passed: 0; failed: 2
