Running Move unit tests
[ PASS    ] 0x1::M::correct_abort_code
[ PASS    ] 0x1::M::just_test_failure
[ FAIL    ] 0x1::M::unexpected_abort
[ FAIL    ] 0x1::M::unexpected_abort_in_other_function
[ FAIL    ] 0x1::M::wrong_abort_code

Test failures:

Failures in 0x1::M:

┌── unexpected_abort ──────
│ Test was not expected to abort but it aborted with 0 here
└──────────────────


┌── unexpected_abort_in_other_function ──────
│ Test was not expected to abort but it aborted with 1 here
└──────────────────


┌── wrong_abort_code ──────
│ Test did not abort with expected code. Expected test to abort with 1 but instead it aborted with 0 here
└──────────────────

Test result: FAILED. Total tests: 5; passed: 2; failed: 3
