[package]
name = "extract-ethereum-abi"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Extract Etherem ABI"
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# move dependencies
move-to-yul = { path = "../move-to-yul" }

# external dependencies
anyhow = { workspace = true }
atty = { workspace = true }
clap = { workspace = true }
codespan-reporting = { workspace = true }
serde_json = { workspace = true }
