version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      # The undocumented default is to open prs for only direct dependencies.
      - dependency-type: direct
    schedule:
      interval: "monthly"
    labels:
      - "cargo"
      - "dependencies"
    ignore:
      - dependency-name: "codespan*"
      - dependency-name: "libfuzzer-sys"
      - dependency-name: "bindgen"
    open-pull-requests-limit: 0
