[package]
name = "read-write-set-dynamic"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Read/write set inference for Move bytecode programs by concretizing the static analysis result"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
move-binary-format = { path = "../../../move-binary-format" }
move-bytecode-utils = { path = "../../move-bytecode-utils" }
move-core-types = { path = "../../../move-core/types" }
move-read-write-set-types = { path = "../types" }
