processed 4 tasks

task 2 'run'. lines 25-39:
Error: Script execution failed with VMError: {
    major_status: STLOC_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 6)],
}

task 3 'run'. lines 41-55:
Error: Script execution failed with VMError: {
    major_status: CALL_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}
