Command `sandbox publish`:
Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M2.mv --struct C --type-args u64`:
---
"0x1::M2::C<u64>":
  STRUCT:
    - t: U64
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M2.mv --struct C --type-args address`:
---
"0x1::M2::C<AccountAddress>":
  STRUCT:
    - t:
        TYPENAME: AccountAddress
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M2.mv --struct C --type-args vector<u8>`:
---
"0x1::M2::C<vector<u8>>":
  STRUCT:
    - t: BYTES
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct B --type-args bool`:
---
"0x1::M1::B<bool>":
  STRUCT:
    - a:
        TYPENAME: AccountAddress
    - c:
        TYPENAME: "0x1::M2::C<bool>"
    - t: BOOL
"0x1::M2::C<bool>":
  STRUCT:
    - t: BOOL
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct B --type-args bool --shallow`:
---
"0x1::M1::B<bool>":
  STRUCT:
    - a:
        TYPENAME: AccountAddress
    - c:
        TYPENAME: "0x1::M2::C<bool>"
    - t: BOOL

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct A --type-args 0x1::M1::S<u64>`:
---
"0x1::M1::A<0x1::M1::S<u64>>":
  STRUCT:
    - f: U64
    - v: BYTES
    - b:
        TYPENAME: "0x1::M1::B<0x1::M1::S<u64>>"
"0x1::M1::B<0x1::M1::S<u64>>":
  STRUCT:
    - a:
        TYPENAME: AccountAddress
    - c:
        TYPENAME: "0x1::M2::C<0x1::M1::S<u64>>"
    - t:
        TYPENAME: "0x1::M1::S<u64>"
"0x1::M1::S<u64>":
  STRUCT:
    - t: U64
"0x1::M2::C<0x1::M1::S<u64>>":
  STRUCT:
    - t:
        TYPENAME: "0x1::M1::S<u64>"
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct A --type-args vector<0x1::M1::S<u64>>`:
---
"0x1::M1::A<vector<0x1::M1::S<u64>>>":
  STRUCT:
    - f: U64
    - v: BYTES
    - b:
        TYPENAME: "0x1::M1::B<vector<0x1::M1::S<u64>>>"
"0x1::M1::B<vector<0x1::M1::S<u64>>>":
  STRUCT:
    - a:
        TYPENAME: AccountAddress
    - c:
        TYPENAME: "0x1::M2::C<vector<0x1::M1::S<u64>>>"
    - t:
        SEQ:
          TYPENAME: "0x1::M1::S<u64>"
"0x1::M1::S<u64>":
  STRUCT:
    - t: U64
"0x1::M2::C<vector<0x1::M1::S<u64>>>":
  STRUCT:
    - t:
        SEQ:
          TYPENAME: "0x1::M1::S<u64>"
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct A --type-args 0x1::M1::S<u64> --shallow`:
---
"0x1::M1::A<0x1::M1::S<u64>>":
  STRUCT:
    - f: U64
    - v: BYTES
    - b:
        TYPENAME: "0x1::M1::B<0x1::M1::S<u64>>"

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct A --type-args vector<0x1::M1::S<u64>> --shallow`:
---
"0x1::M1::A<vector<0x1::M1::S<u64>>>":
  STRUCT:
    - f: U64
    - v: BYTES
    - b:
        TYPENAME: "0x1::M1::B<vector<0x1::M1::S<u64>>>"

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M2.mv --struct C --type-args 0x1::M2::C<u64>`:
---
"0x1::M2::C<0x1::M2::C<u64>>":
  STRUCT:
    - t:
        TYPENAME: "0x1::M2::C<u64>"
    - b: BOOL
"0x1::M2::C<u64>":
  STRUCT:
    - t: U64
    - b: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

Command `sandbox generate struct-layouts --module storage/0x00000000000000000000000000000001/modules/M1.mv --struct G`:
---
"0x1::M1::G<>":
  STRUCT:
    - x: U64
    - s:
        TYPENAME: "0x1::M1::S<bool>"
"0x1::M1::S<bool>":
  STRUCT:
    - t: BOOL
AccountAddress:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16
Signer:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 16

