[package]
name = "move-ethereum-abi"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move Ethereum ABI"
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# external dependencies
ethabi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
doctest = false
