[package]
name = "move-async-vm"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Wrapper for the Move VM for the asynchronous execution flavor"
repository = "https://github.com/diem/move"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.52"
better_any = "0.1.1"
walkdir = "2.3.1"
itertools = "0.10.0"
smallvec = "1.6.1"
sha3 = "0.9.1"
move-command-line-common = { path = "../../../move-command-line-common" }
move-core-types = { path = "../../../move-core/types" }
move-compiler = { path = "../../../move-compiler" }
move-vm-types = { path = "../../../move-vm/types" }
move-vm-runtime = { path = "../../../move-vm/runtime", features = ["debugging"] }
move-vm-test-utils = { path = "../../../move-vm/test-utils" }
move-binary-format = { path = "../../../move-binary-format" }

bcs.workspace = true

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { path = "../../../move-prover/test-utils" }
move-stdlib = { path = "../../../move-stdlib", features = ["testing"] }

[[test]]
name = "testsuite"
harness = false
