[package]
name = "move-ir-to-bytecode-syntax"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem ir to bytecode syntax"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
hex = "0.4.3"
move-ir-types = { path = "../../../move-ir/types" }
move-core-types = { path = "../../../move-core/types" }
move-symbol-pool = { path = "../../../move-symbol-pool" }
move-command-line-common = { path = "../../../move-command-line-common" }

[features]
default = []
