[package]
name = "move-table-extension"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Wrapper for the Move VM which coordinates multiple extensions"
repository = "https://github.com/diem/move"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
better_any = { workspace = true }
bytes = { workspace = true }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-types = { path = "../../move-vm/types" }
sha3 = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
move-cli = { path = "../../tools/move-cli" }
move-package = { path = "../../tools/move-package" }
move-stdlib = { path = "../../move-stdlib", features = ["testing"] }
move-unit-test = { path = "../../tools/move-unit-test", features = ["table-extension"] }
tempfile = { workspace = true }
