Move prover returns: exiting with verification errors
error: abort not covered by any of the `aborts_if` clauses
    ┌─ tests/sources/functional/type_reflection.move:99:5
    │
 97 │           type_info::type_of<T>()
    │           ----------------------- abort happened here with execution failure
 98 │       }
 99 │ ╭     spec test_type_info_can_abort {
100 │ │         // this should not pass
101 │ │         aborts_if false;
102 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/functional/type_reflection.move:97: test_type_info_can_abort
    =         ABORTED
