processed 192 tasks

task 0 'run'. lines 1-11:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 1 'run'. lines 13-18:
Error: ParserError: Invalid Token: unrecognized token kind U16Value

task 2 'run'. lines 20-25:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 3 'run'. lines 28-33:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4 'run'. lines 36-41:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5 'run'. lines 44-49:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 6 'run'. lines 52-57:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'run'. lines 60-65:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8 'run'. lines 68-73:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 9 'run'. lines 76-81:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 10 'run'. lines 84-89:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 11 'run'. lines 92-97:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 12 'run'. lines 100-105:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 13 'publish'. lines 108-116:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 14 'publish'. lines 118-126:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 15 'publish'. lines 128-140:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 16 'run'. lines 141-146:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 17 'run'. lines 149-154:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 18 'run'. lines 157-162:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 19 'run'. lines 165-170:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 20 'run'. lines 173-178:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 21 'run'. lines 181-186:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 22 'run'. lines 189-194:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 23 'run'. lines 197-202:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 24 'run'. lines 205-210:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 25 'run'. lines 213-218:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 26 'run'. lines 221-226:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 27 'run'. lines 229-234:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 28 'publish'. lines 237-245:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 29 'publish'. lines 247-255:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 30 'publish'. lines 257-269:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 31 'run'. lines 270-275:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 32 'run'. lines 278-283:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 33 'run'. lines 286-291:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 34 'run'. lines 294-299:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 35 'run'. lines 302-307:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 36 'run'. lines 310-315:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 37 'run'. lines 318-323:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 38 'run'. lines 326-331:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 39 'run'. lines 334-339:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 40 'run'. lines 342-347:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 41 'run'. lines 350-355:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 42 'run'. lines 358-363:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 43 'publish'. lines 366-374:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 44 'publish'. lines 376-384:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 45 'publish'. lines 386-398:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 46 'run'. lines 399-404:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 47 'run'. lines 407-412:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 48 'run'. lines 415-420:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 49 'run'. lines 423-428:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 50 'run'. lines 431-436:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 51 'run'. lines 439-444:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 52 'run'. lines 447-452:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 53 'run'. lines 455-460:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 54 'run'. lines 463-468:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 55 'run'. lines 471-476:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 56 'run'. lines 479-484:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 57 'run'. lines 487-492:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 58 'publish'. lines 495-503:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 59 'publish'. lines 505-513:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 60 'publish'. lines 515-527:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 61 'run'. lines 528-533:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 62 'run'. lines 536-541:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 63 'run'. lines 544-549:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 64 'run'. lines 552-557:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 65 'run'. lines 560-565:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 66 'run'. lines 568-573:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 67 'run'. lines 576-581:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 68 'run'. lines 584-589:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 69 'run'. lines 592-597:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 70 'run'. lines 600-605:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 71 'run'. lines 608-613:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 72 'run'. lines 616-621:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 73 'publish'. lines 624-632:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 74 'publish'. lines 634-642:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 75 'publish'. lines 644-656:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 76 'run'. lines 657-662:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 77 'run'. lines 665-670:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 78 'run'. lines 673-678:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 79 'run'. lines 681-686:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 80 'run'. lines 689-694:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 81 'run'. lines 697-702:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 82 'run'. lines 705-710:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 83 'run'. lines 713-718:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 84 'run'. lines 721-726:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 85 'run'. lines 729-734:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 86 'run'. lines 737-742:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 87 'run'. lines 745-750:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 88 'publish'. lines 753-761:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 89 'publish'. lines 763-771:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 90 'publish'. lines 773-785:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 91 'run'. lines 786-791:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 92 'run'. lines 794-799:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 93 'run'. lines 802-807:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 94 'run'. lines 810-815:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 95 'run'. lines 818-823:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 96 'run'. lines 826-831:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 97 'run'. lines 834-839:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 98 'run'. lines 842-847:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 99 'run'. lines 850-855:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 100 'run'. lines 858-863:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 101 'run'. lines 866-871:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 102 'run'. lines 874-879:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 103 'publish'. lines 882-890:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 104 'publish'. lines 892-900:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 105 'publish'. lines 902-914:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 106 'run'. lines 915-920:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 107 'run'. lines 923-928:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 108 'run'. lines 931-936:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 109 'run'. lines 939-944:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 110 'run'. lines 947-952:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 111 'run'. lines 955-960:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 112 'run'. lines 963-968:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 113 'run'. lines 971-976:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 114 'run'. lines 979-984:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 115 'run'. lines 987-992:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 116 'publish'. lines 995-1003:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 117 'publish'. lines 1005-1016:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 118 'run'. lines 1017-1022:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 119 'run'. lines 1025-1030:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 120 'run'. lines 1033-1038:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 121 'run'. lines 1041-1046:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 122 'run'. lines 1049-1054:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 123 'run'. lines 1057-1062:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 124 'run'. lines 1065-1070:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 125 'run'. lines 1073-1078:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 126 'run'. lines 1081-1086:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 127 'run'. lines 1089-1094:
Error: Script execution failed with VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 128 'publish'. lines 1097-1105:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 129 'publish'. lines 1107-1119:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 130 'run'. lines 1120-1125:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 131 'run'. lines 1128-1133:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 132 'run'. lines 1136-1141:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 133 'run'. lines 1144-1149:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 134 'run'. lines 1152-1157:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 135 'run'. lines 1160-1165:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 136 'run'. lines 1168-1173:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 137 'run'. lines 1176-1181:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 138 'run'. lines 1184-1189:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 139 'run'. lines 1192-1200:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 140 'run'. lines 1201-1206:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 141 'run'. lines 1209-1214:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 142 'run'. lines 1217-1222:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 143 'run'. lines 1225-1230:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 144 'run'. lines 1233-1238:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 145 'run'. lines 1241-1246:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 146 'run'. lines 1249-1254:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 147 'run'. lines 1257-1262:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 148 'run'. lines 1265-1270:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 149 'run'. lines 1273-1281:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 150 'run'. lines 1282-1287:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 151 'run'. lines 1290-1295:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 152 'run'. lines 1298-1303:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 153 'run'. lines 1306-1311:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 154 'run'. lines 1314-1319:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 155 'run'. lines 1322-1327:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 156 'run'. lines 1330-1335:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 157 'run'. lines 1338-1343:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 158 'run'. lines 1346-1351:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 159 'run'. lines 1354-1362:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 160 'run'. lines 1363-1368:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 161 'run'. lines 1371-1376:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 162 'run'. lines 1379-1384:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 163 'run'. lines 1387-1392:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 164 'run'. lines 1395-1400:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 165 'run'. lines 1403-1408:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 166 'run'. lines 1411-1416:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 167 'run'. lines 1419-1424:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 168 'run'. lines 1427-1432:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 169 'run'. lines 1435-1443:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 170 'run'. lines 1444-1449:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 171 'run'. lines 1452-1457:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 172 'run'. lines 1460-1465:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 173 'run'. lines 1468-1473:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 174 'run'. lines 1476-1481:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 175 'run'. lines 1484-1489:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 176 'run'. lines 1492-1497:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 177 'run'. lines 1500-1505:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 178 'publish'. lines 1508-1516:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 179 'publish'. lines 1518-1526:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 180 'publish'. lines 1528-1540:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 181 'run'. lines 1541-1546:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 182 'run'. lines 1549-1554:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 183 'run'. lines 1557-1562:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 184 'run'. lines 1565-1570:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 185 'run'. lines 1573-1578:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 186 'run'. lines 1581-1586:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 187 'run'. lines 1589-1594:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 188 'run'. lines 1597-1602:
Error: Script execution failed with VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 189 'publish'. lines 1605-1613:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 190 'publish'. lines 1615-1623:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 191 'publish'. lines 1625-1633:
Error: Unable to publish module '00000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}
