[package]
name = "move-vm-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Types for Move VM"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
derivative = "2.2.0"
itertools = "0.10.0"
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.124", features = ["derive", "rc"] }
smallbitvec = "2.5.1"
smallvec = "1.6.1"
triomphe = "0.1.9"

bcs = { workspace = true }

move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }

[dev-dependencies]
claims = "0.7"
move-binary-format = { path = "../../move-binary-format", features = ["fuzzing"] }
proptest = "1.0.0"
rand = "0.8.5"

[features]
default = []
fuzzing = ["proptest", "move-binary-format/fuzzing"]
