[package]
name = "move-vm-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Types for Move VM"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
derivative = { workspace = true }
itertools = { workspace = true }
proptest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
smallbitvec = { workspace = true }
smallvec = { workspace = true }
triomphe = { workspace = true }

bcs = { workspace = true }

move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }

[dev-dependencies]
claims = { workspace = true }
move-binary-format = { path = "../../move-binary-format", features = ["fuzzing"] }
proptest = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "move-binary-format/fuzzing"]
