[package]
name = "move-compiler-v2"
version = "0.1.0"
authors = ["Aptos Labs"]
description = "Move compiler based on stackless bytecode"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptosfoundation.org/"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
abstract-domain-derive = { path = "../move-model/bytecode/abstract_domain_derive" }
anyhow = { workspace = true }
bcs = { workspace = true }
move-binary-format = { path = "../move-binary-format" }
move-bytecode-source-map = { path = "../move-ir-compiler/move-bytecode-source-map" }
move-command-line-common = { path = "../move-command-line-common" }
#move-package = { path = "../tools/move-package" }
move-compiler = { path = "../move-compiler" }
move-core-types = { path = "../move-core/types" }
move-disassembler = { path = "../tools/move-disassembler" }
move-ir-types = { path = "../move-ir/types" }
move-model = { path = "../move-model" }
move-stackless-bytecode = { path = "../move-model/bytecode" }
move-symbol-pool = { path = "../move-symbol-pool" }

clap = { workspace = true, features = ["derive", "env"] }
codespan-reporting = { workspace = true, features = ["serde", "serialization"] }
ethnum = { workspace = true }
flexi_logger = { workspace = true }
im = "15.0.0"
itertools = { workspace = true }
log = { workspace = true, features = ["serde"] }
num = { workspace = true }
once_cell = { workspace = true }
#paste = "1.0.5"
petgraph = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
datatest-stable = { workspace = true }
move-command-line-common = { path = "../move-command-line-common" }
move-ir-types = { path = "../move-ir/types" }
move-prover-test-utils = { path = "../move-prover/test-utils" }
move-stdlib = { path = "../move-stdlib" }
walkdir = { workspace = true }

[lib]
doctest = false

[[test]]
name = "testsuite"
harness = false
doctest = false
