[package]
name = "move-command-line-common"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move shared command line and file tools"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
difference = "2.0.0"
dirs-next = "2.0.0"
hex = "0.4.3"
num-bigint = "0.4.0"
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }
sha2 = "0.9.3"
walkdir = "2.3.1"

move-core-types = { path = "../move-core/types" }
