CompiledPackageInfo {
    package_name: "test",
    address_alias_instantiation: {
        "A": 00000000000000000000000000000001,
        "C": 00000000000000000000000000000003,
        "DA": 00000000000000000000000000000002,
    },
    module_resolution_metadata: {
        ModuleId {
            address: 00000000000000000000000000000001,
            name: Identifier(
                "A",
            ),
        }: "A",
        ModuleId {
            address: 00000000000000000000000000000002,
            name: Identifier(
                "A",
            ),
        }: "DA",
        ModuleId {
            address: 00000000000000000000000000000003,
            name: Identifier(
                "A",
            ),
        }: "C",
    },
    source_digest: Some(
        "ELIDED_FOR_TEST",
    ),
    build_flags: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
        additional_named_addresses: {},
    },
}
