[package]
name = "move-docgen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# diem dependencies
move-compiler = { path = "../../move-compiler" }
move-model = { path = "../../move-model" }

# external dependencies
codespan = "0.11.1"
codespan-reporting = "0.11.1"
itertools = "0.10.0"
log = "0.4.14"
num = "0.4.0"
regex = "1.5.5"
anyhow = "1.0.52"
serde = { version = "1.0.124", features = ["derive"] }
once_cell = "1.7.2"

[dev-dependencies]
move-prover = { path = ".." }
datatest-stable = "0.1.1"
tempfile = "3.2.0"
move-prover-test-utils = { path = "../test-utils" }

[[test]]
name = "testsuite"
harness = false
