warning[W09008]: unused &mut qualifier
   ┌─ tests/move_check/borrows/borrow_field_combo.move:11:43
   │
11 │     fun t0(cond: bool, outer: &mut Outer, other: &mut Outer) {
   │                                           ^^^^^ Unused '&mut' qualifier on parameter 'other'. Consider replacing with an immutable qualifer or prefixing with an underscore: _other

warning[W09008]: unused &mut qualifier
   ┌─ tests/move_check/borrows/borrow_field_combo.move:63:43
   │
63 │     fun t1(cond: bool, outer: &mut Outer, other: &mut Outer) {
   │                                           ^^^^^ Unused '&mut' qualifier on parameter 'other'. Consider replacing with an immutable qualifer or prefixing with an underscore: _other

