[package]
name = "move-prover-test-utils"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
move-command-line-common = { path = "../../move-command-line-common" }
prettydiff = { version = "0.6.2", default-features = false }
regex = "1.5.5"
