[package]
name = "module-generation"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem binary module generation"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
rand = "0.8.3"

move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-ir-to-bytecode = { path = "../../move-ir-compiler/move-ir-to-bytecode" }
move-core-types = { path = "../../move-core/types" }
move-ir-types = { path = "../../move-ir/types" }
move-binary-format = { path = "../../move-binary-format" }
move-symbol-pool = { path = "../../move-symbol-pool" }

[features]
default = []
