[package]
name = "move-binary-format"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move Binary Format"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
arbitrary = { version = "1.1.7", optional = true, features = ["derive"] }
indexmap = "1.9.3"
move-core-types = { path = "../move-core/types" }
once_cell = "1.7.2"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
ref-cast = "1.0.6"
serde = { version = "1.0.124", default-features = false }
variant_count = "1.1.0"

[dev-dependencies]
move-core-types = { path = "../move-core/types", features = ["fuzzing" ] }
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = "1.0.64"

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "arbitrary", "move-core-types/fuzzing"]
