[package]
name = "move-symbol-pool"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "A static, global string table for Move tools"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }


[dev-dependencies]
serde_json = { version = "1.0.64" }

[features]
default = []
