[package]
name = "move-compiler"
version = "0.0.1"
authors = ["Diem Association <opensource@diem.com>"]
description = "The definition of the Move source language, and its compiler"
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
codespan-reporting = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
petgraph = { workspace = true }
regex = { workspace = true }
sha3 = { workspace = true }
tempfile = { workspace = true }

bcs = { workspace = true }

move-binary-format = { path = "../move-binary-format" }
move-borrow-graph = { path = "../move-borrow-graph" }
move-bytecode-source-map = { path = "../move-ir-compiler/move-bytecode-source-map" }
move-bytecode-verifier = { path = "../move-bytecode-verifier" }
move-command-line-common = { path = "../move-command-line-common" }
move-core-types = { path = "../move-core/types" }
move-ir-to-bytecode = { path = "../move-ir-compiler/move-ir-to-bytecode" }
move-ir-types = { path = "../move-ir/types" }
move-symbol-pool = { path = "../move-symbol-pool" }

[dev-dependencies]
datatest-stable = { workspace = true }
move-stdlib = { path = "../move-stdlib" }

[[test]]
name = "move_check_testsuite"
harness = false
