[package]
name = "move-compiler"
version = "0.0.1"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
codespan-reporting = "0.11.1"
hex = "0.4.3"
regex = "1.4.3"
clap = { version = "3.1.8", features = ["derive"] }
difference = "2.0.0"
petgraph = "0.5.1"
walkdir = "2.3.1"
tempfile = "3.2.0"
once_cell = "1.7.2"
num-bigint = "0.4.0"
sha3 = "0.9.1"

move-binary-format = { path = "../move-binary-format" }
move-core-types = { path = "../move-core/types" }
move-bytecode-verifier = { path = "../move-bytecode-verifier" }
move-symbol-pool = { path = "../move-symbol-pool" }
move-ir-types = { path = "../move-ir/types" }
move-ir-to-bytecode = { path = "../move-ir-compiler/move-ir-to-bytecode" }
move-borrow-graph = { path = "../move-borrow-graph" }
move-bytecode-source-map = { path = "../move-ir-compiler/move-bytecode-source-map" }
bcs = "0.1.2"
move-command-line-common = { path = "../move-command-line-common" }

[dev-dependencies]
move-stdlib = { path = "../move-stdlib" }
datatest-stable = "0.1.1"

[[test]]
name = "move_check_testsuite"
harness = false
