[package]
name = "move-errmapgen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
bcs = { workspace = true }
# Move dependencies
move-command-line-common = { path = "../../move-command-line-common" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = "../../move-model" }

# external dependencies
log = "0.4.14"
serde = { version = "1.0.124", features = ["derive"] }

[dev-dependencies]
codespan-reporting = "0.11.1"
datatest-stable = "0.1.1"
move-prover = { path = ".." }
