[package]
name = "move-errmapgen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
# Move dependencies
move-command-line-common = { path = "../../move-command-line-common" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = "../../move-model" }

# external dependencies
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
codespan-reporting = { workspace = true }
datatest-stable = { workspace = true }
move-prover = { path = ".." }
