warning[W09008]: unused &mut qualifier
   ┌─ tests/move_check/unused_mut/call_warn.move:11:26
   │
11 │     fun call_read_vector(f: &mut vector<u64>) {
   │                          ^ Unused '&mut' qualifier on parameter 'f'. Consider replacing with an immutable qualifer: '&'

warning[W09008]: unused &mut qualifier
   ┌─ tests/move_check/unused_mut/call_warn.move:15:25
   │
15 │     fun call_read_field(s: &mut S) {
   │                         ^ Unused '&mut' qualifier on parameter 's'. Consider replacing with an immutable qualifer: '&'

