[package]
name = "df-cli"
version = "0.1.0"
description = "CLI frontend for the Move compiler and VM (with Diem Framework)"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.1.8", features = ["derive"] }

bcs = "0.1.4"

move-stdlib = { path = "../../../../../move-stdlib" }
move-core-types = { path = "../../../../../move-core/types" }
move-vm-types = { path = "../../../../../move-vm/types" }
move-cli = { path = "../../../../../tools/move-cli" }
move-vm-test-utils = { path = "../../../../../move-vm/test-utils" }

diem-framework-natives = { path = "../natives" }

[dev-dependencies]
datatest-stable = "0.1.1"
