[package]
name = "move-prover-bytecode-pipeline"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
abstract-domain-derive = { path = "../../move-model/bytecode/abstract_domain_derive" }
anyhow = "1.0.52"
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = "../../move-model" }

# move dependencies
move-stackless-bytecode = { path = "../../move-model/bytecode" }

# external dependencies
codespan-reporting = "0.11.1"
itertools = "0.10.0"
log = { version = "0.4.14", features = ["serde"] }
serde = { version = "1.0.124", features = ["derive"] }

[dev-dependencies]
datatest-stable = "0.1.1"
move-stackless-bytecode-test-utils = { path = "../../move-model/bytecode-test-utils" }
shell-words = "1.0.0"
tempfile = "3.2.0"
walkdir = "2.3.1"

[[test]]
name = "testsuite"
harness = false
