[package]
name = "move-stackless-bytecode-interpreter"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# diem dependencies
move-stackless-bytecode = { path = "../bytecode" }
bytecode-interpreter-crypto = { path = "crypto" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = "../../move-model" }

# external dependencies
anyhow = "1.0.52"
codespan-reporting = "0.11.1"
itertools = "0.10.0"
num = "0.4.0"
serde = { version = "1.0.124", features = ["derive"] }
clap = { version = "3.1.8", features = ["derive"] }

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { path = "../test-utils" }
