[package]
name = "move-resource-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem genesis viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-utils = { path = "../move-bytecode-utils" }
move-core-types = { path = "../../move-core/types" }
serde = { workspace = true, features = ["derive", "rc"] }

anyhow = { workspace = true }
hex = { workspace = true }
