[package]
name = "move-resource-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem genesis viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-utils = { path = "../move-bytecode-utils" }
move-core-types = { path = "../../move-core/types" }
serde = { version = "1.0.124", features = ["derive", "rc"] }

bcs = { workspace = true }

anyhow = "1.0.52"
hex = "0.4.3"
once_cell = "1.7.2"
