[package]
name = "move-bytecode-verifier"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move bytecode verifier"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
fail = { workspace = true }
move-binary-format = { path = "../move-binary-format" }
petgraph = { workspace = true }
serde = { workspace = true }
typed-arena = { workspace = true }

move-borrow-graph = { path = "../move-borrow-graph" }
move-core-types = { path = "../move-core/types" }

[dev-dependencies]
hex-literal = { workspace = true }
invalid-mutations = { path = "invalid-mutations" }

[features]
default = []
