[package]
name = "move-bytecode-verifier"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move bytecode verifier"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
petgraph = "0.5.1"

move-borrow-graph = { path = "../move-borrow-graph" }
move-binary-format = { path = "../move-binary-format" }
move-core-types = { path = "../move-core/types" }

[dev-dependencies]
invalid-mutations = { path = "invalid-mutations" }

[features]
default = []
