[package]
name = "bytecode-interpreter-testsuite"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dev-dependencies]

# diem dependencies
move-stackless-bytecode-interpreter = { path = "../interpreter" }
move-command-line-common = { path = "../../move-command-line-common" }
move-prover-test-utils = { path = "../test-utils" }
move-stdlib = { path = "../../move-stdlib" }
move-unit-test = { path = "../../tools/move-unit-test" }

# external dependencies
anyhow = "1.0.52"
datatest-stable = "0.1.1"

[[test]]
name = "concrete_check_testsuite"
harness = false
