[package]
name = "move-read-write-set-types"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
description = "Type definition for read/write set inference for Move bytecode programs"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
move-binary-format = { path = "../../../move-binary-format", version = "0.0.3" }
move-core-types = { path = "../../../move-core/types", version = "0.0.4" }
serde = { version = "1.0.124", default-features = false }
