[package]
name = "move-model"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
move-binary-format = { path = "../move-binary-format" }
move-bytecode-source-map = { path = "../move-ir-compiler/move-bytecode-source-map" }
move-command-line-common = { path = "../move-command-line-common" }
# diem dependencies
move-compiler = { path = "../move-compiler" }
move-core-types = { path = "../move-core/types" }
move-disassembler = { path = "../tools/move-disassembler" }
move-ir-types = { path = "../move-ir/types" }
move-symbol-pool = { path = "../move-symbol-pool" }

# external dependencies
codespan = { workspace = true }
codespan-reporting = { workspace = true }
internment = { workspace = true, features = ["arc"] }
itertools = { workspace = true }
log = { workspace = true }
num = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
datatest-stable = { workspace = true }
move-prover-test-utils = { path = "../move-prover/test-utils" }

[[test]]
name = "testsuite"
harness = false
