[package]
name = "BasicCoin"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "../../../../move-stdlib/", addr_subst = { "std" = "0x1" } }
MoveNursery = { local = "../../../../move-stdlib/nursery", addr_subst = { "std" = "0x1" } }