[package]
name = "move-ir-compiler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move IR to bytecode compiler"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
move-bytecode-verifier = { path = "../move-bytecode-verifier" }
move-command-line-common = { path = "../move-command-line-common" }
move-ir-to-bytecode = { path = "move-ir-to-bytecode" }
move-bytecode-source-map = { path = "move-bytecode-source-map" }
move-ir-types = { path = "../move-ir/types" }
move-core-types = { path = "../move-core/types" }
move-binary-format = { path = "../move-binary-format" }
move-symbol-pool = { path = "../move-symbol-pool" }
clap = { version = "3.1.8", features = ["derive"] }
serde_json = "1.0.64"

bcs.workspace = true

[features]
default = []
