[package]
name = "EvmExamples"
version = "1.5.0"

[addresses]
std = "0x1"
Evm = "0x2"

[dependencies]
MoveStdlib = { local = "../../move-stdlib" }
MoveNursery = { local = "../../move-stdlib/nursery" }
EvmStdlib = { local = "../stdlib" }
