[package]
name = "move-prover-boogie-backend"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move prover Boogie backend"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.42"
move-stackless-bytecode = { path = "../bytecode" }
move-command-line-common = { path = "../../move-command-line-common" }
move-model = { path = "../../move-model" }
move-binary-format = { path = "../../move-binary-format" }
num = "0.4.0"
itertools = "0.10.0"
move-core-types = { path = "../../move-core/types" }
log = "0.4.14"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
anyhow = "1.0.52"
once_cell = "1.7.2"
pretty = "0.10.0"
regex = "1.5.5"
rand = "0.8.3"
futures = "0.3.12"
tera = "1.16.0"
tokio = { version = "1.18.2", features = ["full"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
