CompiledPackageInfo {
    package_name: "Root",
    address_alias_instantiation: {
        "A": 00000000000000000000000000000002,
    },
    source_digest: Some(
        "ELIDED_FOR_TEST",
    ),
    build_flags: BuildConfig {
        dev_mode: true,
        test_mode: false,
        generate_docs: false,
        generate_abis: false,
        install_dir: Some(
            "ELIDED_FOR_TEST",
        ),
        force_recompilation: false,
        additional_named_addresses: {},
        architecture: None,
        only_deps: false,
    },
}
