[package]
name = "move-ir-to-bytecode"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem ir to bytecode"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
move-ir-to-bytecode-syntax = { path = "syntax" }
move-command-line-common = { path = "../../move-command-line-common" }
move-core-types = { path = "../../move-core/types" }
move-ir-types = { path = "../../move-ir/types" }
move-binary-format = { path = "../../move-binary-format" }
move-symbol-pool = { path = "../../move-symbol-pool" }
move-bytecode-source-map = { path = "../move-bytecode-source-map" }
log = "0.4.14"
codespan-reporting = "0.11.1"
thiserror = "1.0.24"
ouroboros = "0.9.2"

[features]
default = []
