Command `package build`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Command `package test --coverage --threads 1`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] 0x1::AModule::double_three
[ PASS    ] 0x1::AModule::double_two
[ PASS    ] 0x1::AModuleTests::double_one_one
[ PASS    ] 0x1::AModuleTests::double_three
[ PASS    ] 0x1::AModuleTests::double_zero_zero
[ PASS    ] 0x1::AModuleTests::double_zero_zero_wrong
Test result: OK. Total tests: 6; passed: 6; failed: 0
Command `package coverage summary --summarize-functions`:
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 00000000000000000000000000000001::AModule
	fun double_except_three
		total: 10
		covered: 10
		% coverage: 100.00
>>> % Module coverage: 100.00
+-------------------------+
| % Move Coverage: 100.00  |
+-------------------------+
Command `package coverage source --module AModule`:
module std::AModule {

    /// x was three
    const E_IS_THREE: u64 = 0;

    public fun double_except_three(x: u64): u64 {
        assert!(x != 3, E_IS_THREE);
        x * x
    }

    #[test]
    fun double_two() {
        assert!(double_except_three(4) == 16, 0)
    }

    #[test]
    #[expected_failure]
    fun double_three() {
        double_except_three(3);
    }
}
Command `package coverage bytecode --module AModule`:
// Move bytecode v5
module 1.AModule {


public double_except_three(x: u64): u64 {
B0:
[6]	0: CopyLoc[0](x: u64)
[6]	1: LdU64(3)
[6]	2: Neq
[6]	3: BrTrue(6)
B1:
[2]	4: LdAddr[0](U64: [0, 0, 0, 0, 0, 0, 0, 0])
[2]	5: Abort
B2:
[4]	6: CopyLoc[0](x: u64)
[4]	7: MoveLoc[0](x: u64)
[4]	8: Mul
[4]	9: Ret
}
}
Command `package disassemble --package MoveStdlib --name signer`:
// Move bytecode v5
module 1.signer {


public address_of(s: &signer): address {
B0:
	0: MoveLoc[0](s: &signer)
	1: Call[1](borrow_address(&signer): &address)
	2: ReadRef
	3: Ret
}
native public borrow_address(s: &signer): &address
}
Command `package errmap`:
Command `package info`:
PackageBasics
├─ std:0x1
└─ MoveStdlib
   └─ std:0x1
