[package]
name = "bytecode-verifier-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem bytecode verifier tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
fail = { workspace = true, features = ['failpoints'] }
hex = { workspace = true }
invalid-mutations = { path = "../invalid-mutations" }
move-binary-format = { path = "../../move-binary-format", features = ["fuzzing"] }
move-bytecode-verifier = { path = "../" }
move-core-types = { path = "../../move-core/types" }
petgraph = { workspace = true }
proptest = { workspace = true }

[features]
fuzzing = ["move-binary-format/fuzzing"]
