[package]
name = "move-bytecode-utils"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Libraries for working with sets of Move bytecode modules"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
petgraph = "0.5.1"
serde-reflection = "0.3.2"
