[package]
name = "x-core"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Core data structures used by x"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
camino = { version = "1.0.3", features = ["serde1"] }
debug-ignore = "1.0.1"
determinator = "0.7.0"
guppy = "0.12.3"
indoc = "1.0.3"
hex = "0.4.3"
log = "0.4.14"
toml = "0.5.8"
once_cell = "1.7.2"
ouroboros = "0.9.2"
serde = { version = "1.0.124", features = ["derive"] }
