[package]
name = "move-abigen"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# Move dependencies
move-model = { path = "../../move-model" }
move-core-types = { path = "../../move-core/types" }
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-command-line-common = { path = "../../move-command-line-common" }

bcs.workspace = true

# external dependencies
log = "0.4.14"
anyhow = "1.0.52"
heck = "0.3.2"
serde = { version = "1.0.124", features = ["derive"] }

[dev-dependencies]
codespan-reporting = "0.11.1"
move-prover = { path = ".." }
datatest-stable = "0.1.1"
tempfile = "3.2.0"
move-prover-test-utils = { path = "../test-utils" }

[[test]]
name = "testsuite"
harness = false
