[package]
name = "move-vm-integration-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move VM Integration Tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
memory-stats = { workspace = true }
move-binary-format = { path = "../../move-binary-format" }
move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-compiler = { path = "../../move-compiler" }
smallvec = { workspace = true }
tempfile = { workspace = true }

move-core-types = { path = "../../move-core/types" }
move-stdlib = { path = "../../move-stdlib" }
move-vm-runtime = { path = "../runtime", features = ["testing"] }
move-vm-test-utils = { path = "../test-utils" }
move-vm-types = { path = "../types" }

[features]
default = []
table-extension = [
    "move-vm-test-utils/table-extension"
]
