[package]
name = "move-compiler-v2-transactional-tests"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
move-command-line-common = { path = "../../move-command-line-common" }
once_cell = "1.7.2"

[dev-dependencies]
datatest-stable = "0.1.1"
itertools = "0.10.3"
move-compiler-v2 = { path = ".." }
move-transactional-test-runner = { path = "../../testing-infra/transactional-test-runner" }
walkdir = "2.3.3"

[[test]]
name = "tests"
harness = false
