[package]
name = "move-prover"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# move dependencies
move-prover-boogie-backend = { path = "boogie-backend" }
move-command-line-common = { path = "../move-command-line-common" }
move-binary-format = { path = "../move-binary-format" }
move-compiler = { path = "../move-compiler" }
move-model = { path = "../move-model" }
move-docgen = { path = "move-docgen" }
move-abigen = { path = "move-abigen" }
move-errmapgen = { path = "move-errmapgen" }
move-stackless-bytecode = { path = "bytecode" }
move-ir-types = { path = "../move-ir/types" }
move-core-types = { path = "../move-core/types" }

# external dependencies
async-trait = "0.1.42"
anyhow = "1.0.52"
atty = "0.2.14"
clap = { version = "3.1.8", features = ["derive"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
futures = "0.3.12"
hex = "0.4.3"
itertools = "0.10.0"
log = { version = "0.4.14", features = ["serde"] }
num = "0.4.0"
pretty = "0.10.0"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
simplelog = "0.9.0"
once_cell = "1.7.2"
tokio = { version = "1.18.2", features = ["full"] }
toml = "0.5.8"

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { path = "test-utils" }
shell-words = "1.0.0"
walkdir = "2.3.1"
tempfile = "3.2.0"

[[test]]
name = "testsuite"
harness = false
