[package]
name = "move-prover"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.52"
move-abigen = { path = "move-abigen" }
move-command-line-common = { path = "../move-command-line-common" }
move-compiler = { path = "../move-compiler" }
move-compiler-v2 = { path = "../move-compiler-v2" }
move-docgen = { path = "move-docgen" }
move-errmapgen = { path = "move-errmapgen" }
move-model = { path = "../move-model" }
# move dependencies
move-prover-boogie-backend = { path = "boogie-backend" }
move-prover-bytecode-pipeline = { path = "bytecode-pipeline" }
move-stackless-bytecode = { path = "../move-model/bytecode" }

# external dependencies
atty = "0.2.14"
clap = { version = "4.3.9", features = ["derive"] }
codespan-reporting = "0.11.1"
itertools = "0.10.0"
log = { version = "0.4.14", features = ["serde"] }
once_cell = "1.7.2"
serde = { version = "1.0.124", features = ["derive"] }
simplelog = "0.9.0"
toml = "0.5.8"

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { path = "test-utils" }
shell-words = "1.0.0"
tempfile = "3.2.0"
walkdir = "2.3.1"

[[test]]
name = "testsuite"
harness = false
