[package]
name = "move-prover"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
move-abigen = { path = "move-abigen" }
move-command-line-common = { path = "../move-command-line-common" }
move-compiler = { path = "../move-compiler" }
move-compiler-v2 = { path = "../move-compiler-v2" }
move-docgen = { path = "move-docgen" }
move-errmapgen = { path = "move-errmapgen" }
move-model = { path = "../move-model" }
# move dependencies
move-prover-boogie-backend = { path = "boogie-backend" }
move-prover-bytecode-pipeline = { path = "bytecode-pipeline" }
move-stackless-bytecode = { path = "../move-model/bytecode" }

# external dependencies
atty = { workspace = true }
clap = { workspace = true, features = ["derive"] }
codespan-reporting = { workspace = true }
itertools = { workspace = true }
log = { workspace = true, features = ["serde"] }
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simplelog = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
datatest-stable = { workspace = true }
move-prover-test-utils = { path = "test-utils" }
shell-words = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }

[[test]]
name = "testsuite"
harness = false
