[package]
name = "prover-lab"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
# diem dependencies
move-compiler = { path = "../../move-compiler" }
move-model = { path = "../../move-model" }
move-prover = { path = ".." }
move-prover-boogie-backend = { path = "../boogie-backend" }
move-prover-bytecode-pipeline = { path = "../bytecode-pipeline" }

# FB external dependencies
z3tracer = "0.8.0"

# external dependencies
anyhow = "1.0.52"
chrono = "0.4.19"
clap = { version = "4.3.9", features = ["derive"] }
codespan-reporting = "0.11.1"
itertools = "0.10.0"
log = { version = "0.4.14", features = ["serde"] }
plotters = { version = "0.3.5", default_features = false, features = [
    "evcxr",
    "line_series",
    "histogram",
] }
