processed 9 tasks

task 1 'run'. lines 29-33:
ChangeSet: ChangeSet { accounts: {} }


task 2 'run'. lines 35-39:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#0: false

task 3 'run'. lines 41-46:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#1: false, local#3: { 0 }

task 4 'run'. lines 48-52:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#1: false, local#3: { 0 }

task 5 'run'. lines 54-54:
ChangeSet: ChangeSet { accounts: {} }


task 6 'run'. lines 56-56:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#0: false

task 7 'run'. lines 58-58:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#1: false, local#3: { 0 }

task 8 'run'. lines 60-60:
ChangeSet: ChangeSet { accounts: {} }
mutable inputs after call: local#1: false, local#3: { 0 }
