[package]
name = "test-generation"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Tool for generating tests for the bytecode verifier and Move VM runtime"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
crossbeam-channel = "0.5.0"
getrandom = "0.2.2"
hex = "0.4.3"
itertools = "0.10.0"
module-generation = { path = "../module-generation" }
move-binary-format = { path = "../../move-binary-format" }
num_cpus = "1.13.0"
once_cell = "1.7.2"
rand = "0.8.3"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-compiler = { path = "../../move-compiler" }
move-core-types = { path = "../../move-core/types" }
move-stdlib = { path = "../../move-stdlib" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-test-utils = { path = "../../move-vm/test-utils" }
move-vm-types = { path = "../../move-vm/types" }
