[package]
name = "test-generation"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Tool for generating tests for the bytecode verifier and Move VM runtime"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
crossbeam-channel = { workspace = true }
getrandom = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
module-generation = { path = "../module-generation" }
num_cpus = { workspace = true }
once_cell = { workspace = true }
# Cannot use workspace version as aptos-core currently cannot be upgraded
# to newer rand. See https://github.com/aptos-labs/aptos-core/issues/13031
rand = { version = "0.8.5" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

move-binary-format = { path = "../../move-binary-format" }
move-bytecode-verifier = { path = "../../move-bytecode-verifier" }
move-compiler = { path = "../../move-compiler" }
move-core-types = { path = "../../move-core/types" }
move-stdlib = { path = "../../move-stdlib" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-test-utils = { path = "../../move-vm/test-utils" }
move-vm-types = { path = "../../move-vm/types" }
