[package]
name = "diem-crypto-derive"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.64", features = ["derive"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"

[dev-dependencies]
anyhow = "1.0.52"
