name: "Acquire Solana Tools"
description: |
  Get Solana's Build of LLVM and platform-tools from GitHub Actions artifacts.
inputs:
  github-token:
    description: GitHub token
    required: true
runs:
  using: "composite"
  steps:
    - name: Download LLVM
      shell: bash
      run: |
        mkdir ../llvm
        curl -L https://github.com/solana-labs/platform-tools/releases/download/v1.38/move-dev-linux-x86_64.tar.bz2 \
             -o ../llvm/move-dev-linux-x86_64.tar.bz2
        ls -lh ../llvm
        (cd ../llvm && tar xjf move-dev-linux-x86_64.tar.bz2)
        ls -lh ../llvm
        # llvm is at ../llvm/move-dev
    - name: Download platform-tools
      shell: bash
      run: |
        mkdir ../platform-tools
        curl -L https://github.com/solana-labs/platform-tools/releases/download/v1.38/platform-tools-linux-x86_64.tar.bz2 \
             -o ../platform-tools/platform-tools.tar.bz2
        ls -lh ../platform-tools
        (cd ../platform-tools && tar xjf platform-tools.tar.bz2)
        ls -lh ../platform-tools
        # platform-tools is at ../platform-tools
