[package]
name = "move-stackless-bytecode"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Move stackless bytecode"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
abstract-domain-derive = { path = "./abstract_domain_derive" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
move-model = { path = ".." }

codespan-reporting = { workspace = true, features = ["serde", "serialization"] }
ethnum = { workspace = true }
im = "15.0.0"
itertools = { workspace = true }
log = { workspace = true }
num = { workspace = true }
paste = { workspace = true }
petgraph = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
datatest-stable = { workspace = true }
move-stackless-bytecode-test-utils = { path = "../bytecode-test-utils" }

[features]
default = []

[[test]]
name = "testsuite"
harness = false
